# Generated by Django 3.2.9 on 2022-02-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsUnit',
        ),
    ]
