# Generated by Django 3.2.9 on 2022-02-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_newsunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='press',
            field=models.IntegerField(default=0),
        ),
    ]
