# Generated by Django 3.2.9 on 2022-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_newsunit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(default='', max_length=100)),
                ('pPrice', models.IntegerField(default=0)),
                ('pDescription', models.TextField(blank=True, default='')),
                ('pQty', models.IntegerField(default=0)),
                ('pImage', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
