# Generated by Django 3.2.9 on 2022-02-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_product_pqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pImage',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
