# Generated by Django 3.2.9 on 2022-02-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220222_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pDescription',
        ),
    ]
